---
title: "hw2"
output: github_document
---


```{r setup}
library(tidyverse)
library(readxl)
```

## Problem 1

Read the Mr. Trashwheel dataset

```{r}
trashwheel_df = 
  read_xlsx("./Trash-Wheel-Collection-Totals-8-6-19.xlsx",
            sheet = "Mr. Trash Wheel",
            range = cell_cols("A:N")
            ) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls=round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )
```

read precipitation data

```{r}
precip_2018=
  read_xlsx("./Trash-Wheel-Collection-Totals-8-6-19.xlsx",
            sheet = "2018 Precipitation",
            skip =1
            ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year=2018) %>% 
  select(year,everything())

precip_2017=
  read_xlsx("./Trash-Wheel-Collection-Totals-8-6-19.xlsx",
            sheet = "2017 Precipitation",
            skip =1
            ) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year=2017) %>% 
  select(year,everything())

```

Combine annual precipitation

```{r}

month_df = tibble(
  month_num = 1:12,
  month_name = month.name
)

precip_df=
  bind_rows(precip_2018,precip_2017)

precip_df = left_join(precip_df,month_df,by = c("month" = "month_num"))
```


This dataset contains information ...












